[meta]
name        = "gaming"
description = "Gaming platform and performance tools"
os          = "linux"

[[packages]]
name   = "steam"
system = "steam"

[[packages]]
name   = "gamemode"
system = "gamemode"
optional = true

[[packages]]
name   = "gamescope"
system = "gamescope"

[[packages]]
name   = "mangohud"
system = "mangohud"
optional = true

[[packages]]
name   = "lib32-mangohud"
system = "lib32-mangohud"
optional = true

[[packages]]
name   = "vkbasalt"
system = "vkbasalt"
optional = true

[[packages]]
name   = "protonplus"
system = "protonplus"

[[packages]]
name   = "cachyos-gaming-meta"
system = "cachyos-gaming-meta"
optional = true

[[packages]]
name   = "goverlay"
system = "goverlay"

[[packages]]
name   = "lutris"
system = "lutris"

[[packages]]
name   = "twintaillauncher-bin"
system    = "twintaillauncher-bin"

[[dotfiles]]
src = "files/.config/MangoHud/MangoHud.conf"
target_linux = "~/.config/MangoHud/MangoHud.conf"
target_mac = "~/.config/MangoHud/MangoHud.conf"
