[meta]
name        = "apps"
description = "GUI applications"
os          = "linux"

[[packages]]
name   = "zen-browser-bin"
system    = "zen-browser-bin"

[[packages]]
name   = "gnome-calculator"
system = "gnome-calculator"

[[packages]]
name   = "gnome-clocks"
system = "gnome-clocks"

[[packages]]
name   = "loupe"
system = "loupe"

[[packages]]
name   = "libreoffice-fresh"
system = "libreoffice-fresh"
optional = true

[[packages]]
name   = "gimp"
system = "gimp"
optional = true

[[packages]]
name   = "krita"
system = "krita"
optional = true

[[packages]]
name   = "pinta"
system    = "pinta"

[[packages]]
name   = "obsidian"
system = "obsidian"
optional = true

[[packages]]
name   = "vesktop-bin"
system    = "vesktop-bin"
optional = true

[[packages]]
name   = "uget"
system = "uget"
optional = true

[[packages]]
name   = "octopi"
system = "octopi"

[[packages]]
name   = "pacseek-bin"
system    = "pacseek-bin"

[[packages]]
name   = "fsearch"
system    = "fsearch"
optional = true

[[dotfiles]]
src = "files/.config/pacseek/config.json"
target_linux = "~/.config/pacseek/config.json"
target_mac = "~/.config/pacseek/config.json"
