unbind-key C-b
set-option -g prefix <
bind-key < send-prefix

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

set -g mouse on
set -g mode-keys vi

source-file ~/.config/tmux/generated.conf

set-environment -g CLAUDE_CODE_TMUX_TRUECOLOR 1
# set-option -g default-terminal "tmux-256color"
# set-option -sa terminal-features ',xterm-kitty:RGB'
# set-option -ga terminal-overrides ',xterm-kitty:Tc'
