vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>')
vim.keymap.set('n', '<leader>q', vim.diagnostic.setloclist, { desc = 'Open diagnostic [Q]uickfix list' })
vim.keymap.set('n', '<leader>gt', '<cmd>cd /mnt/ntfs/HTB/Documents/txt/<cr>', { desc = '[G]o to [T]xt folder' })
vim.keymap.set('n', '<leader>gg', '<cmd>cd /home/htb/Documents/Obsidian Vault/<cr>', { desc = '[G]o to Obsidian vault' })
vim.keymap.set('n', '<leader>gh', '<cmd>cd ~<cr>', { desc = '[G]o to [H]ome' })
vim.keymap.set('n', '<leader>gc', '<cmd>cd ~/.config<cr>', { desc = '[G]o to [C]onfig' })
vim.keymap.set('n', '<leader>gd', '<cmd>cd ~/Documents/code/<cr>', { desc = '[G]o to co[D]e' })
vim.keymap.set('t', '<Esc><Esc>', '<C-\\><C-n>', { desc = 'Exit terminal mode' })
vim.keymap.set('n', '<left>', '<cmd>echo "Use h to move!!"<CR>')
vim.keymap.set('n', '<right>', '<cmd>echo "Use l to move!!"<CR>')
vim.keymap.set('n', '<up>', '<cmd>echo "Use k to move!!"<CR>')
vim.keymap.set('n', '<down>', '<cmd>echo "Use j to move!!"<CR>')
vim.keymap.set('n', '<C-h>', '<C-w><C-h>', { desc = 'Move focus to the left window' })
vim.keymap.set('n', '<C-l>', '<C-w><C-l>', { desc = 'Move focus to the right window' })
vim.keymap.set('n', '<C-j>', '<C-w><C-j>', { desc = 'Move focus to the lower window' })
vim.keymap.set('n', '<C-k>', '<C-w><C-k>', { desc = 'Move focus to the upper window' })
