[meta]
name        = "media"
description = "Audio, video, and music playback"
os          = "linux"

[[packages]]
name   = "mpv"
system = "mpv"

[[packages]]
name   = "mpv-mpris"
system = "mpv-mpris"

[[packages]]
name   = "pavucontrol"
system = "pavucontrol"

[[packages]]
name   = "pipewire-pulse"
system = "pipewire-pulse"

[[packages]]
name   = "wireplumber"
system = "wireplumber"

[[packages]]
name   = "alsa-utils"
system = "alsa-utils"

[[packages]]
name   = "vlc-plugins-all"
system = "vlc-plugins-all"
optional = true

[[packages]]
name   = "libdvdcss"
system = "libdvdcss"
optional = true

[[packages]]
name   = "gst-plugin-va"
system = "gst-plugin-va"
optional = true

[[packages]]
name   = "spicetify-cli"
system = "spicetify-cli"
optional = true

[[packages]]
name   = "yt-dlp"
system = "yt-dlp"
optional = true

[[packages]]
name   = "spotdl"
system = "spotdl"
optional = true

[[packages]]
name   = "quodlibet"
system = "quodlibet"
optional = true

[[packages]]
name   = "spotify"
system = "spotify"
optional = true

[[scripts]]
name = "Enable audio services"
file = "scripts/enable-audio-services.sh"
when = "post_packages"

[[scripts]]
name = "Apply Spicetify theme"
file = "scripts/spicetify-apply.sh"
when = "post_packages"

[[scripts]]
name = "Install/Update uosc"
file = "scripts/install-update-uosc.sh"
when = "post_dotfiles"

[[scripts]]
name = "Clone thumbfast"
file = "scripts/clone-thumbfast.sh"
when = "pre_dotfiles"

[[dotfiles]]
src = "files/.config/mpv"
target_linux = "~/.config/mpv"
target_mac = "~/.config/mpv"

[[dotfiles]]
src = "files/.config/spicetify"
target_linux = "~/.config/spicetify"
target_mac = "~/.config/spicetify"
