[meta]
name        = "terminal-tools"
description = "CLI monitoring and system utilities"
os          = "any"

[[packages]]
name   = "btop"
system = "btop"

[[packages]]
name   = "fastfetch"
system = "fastfetch"

[[packages]]
name   = "htop"
system = "htop"

[[packages]]
name   = "nvtop"
system = "nvtop"

[[packages]]
name   = "gdu"
system = "gdu"

[[packages]]
name   = "wavemon"
system = "wavemon"

[[packages]]
name = "cava"
system = "cava"
optional = true

[[packages]]
name = "ripgrep"
system = "ripgrep"

[[packages]]
name = "fd"
system = "fd"

[[packages]]
name = "viu"
system = "viu"

[[packages]]
name = "bat"
system = "bat"

[[dotfiles]]
src = "files/.config/btop/btop.conf"
target_linux = "~/.config/btop/btop.conf"
target_mac = "~/.config/btop/btop.conf"

[[dotfiles]]
src = "files/.config/fastfetch"
target_linux = "~/.config/fastfetch"
target_mac = "~/.config/fastfetch"
