# set prefix
unbind-key C-b
set-option -g prefix `
bind-key ` send-prefix

# reload tmux config bin
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# some options
set -g mouse on
set -g mode-keys vi
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# theme
source-file ~/.config/tmux/generated.conf

# colors
set-environment -g CLAUDE_CODE_TMUX_TRUECOLOR 1
# set-option -g default-terminal "tmux-256color"
# set-option -sa terminal-features ',xterm-kitty:RGB'
# set-option -ga terminal-overrides ',xterm-kitty:Tc'

# plugins
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
