[meta]
name        = "virt"
description = "QEMU/KVM virtualization stack"
os          = "linux"

[[packages]]
name   = "qemu-full"
system = "qemu-full"

[[packages]]
name   = "virt-manager"
system = "virt-manager"

[[packages]]
name   = "swtpm"
system = "swtpm"
