#  ┏┓┏┓┏┓┏┳┓┳┏┓┓┏  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓
#  ┗┓┃┃┃┃ ┃ ┃┣ ┗┫━━┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃
#  ┗┛┣┛┗┛ ┻ ┻┻ ┗┛  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗
#                                  


[Comfy]
text               = e1e2e9
subtext            = c3c6cf
main               = 111318
main-elevated      = 37393e
main-transition    = 0c0e13
highlight          = 191c20
highlight-elevated = 32353a
sidebar            = 111318
player             = 000000
card               = 000000
shadow             = 000000
selected-row       = e1e2e9
button             = a6c8ff
button-active      = d4e3ff
button-disabled    = a6c8ff
tab-active         = 111318
notification       = dabde2
notification-error = ffb4ab
misc               = 000000
play-button        = bcc7dc
play-button-active = d8e3f8
progress-fg        = a6c8ff
progress-bg        = 111318
heart              = ffb4ab
pagelink-active    = f7d8ff
radio-btn-active   = f7d8ff