-- MONITORS
-- Merged: source/monitors.conf + edit_here/source/monitors.conf
-- Specific monitor rules from edit_here override the fallback, but the
-- fallback is kept so hotplugged displays still work automatically.

-- Fallback: any display not matched below gets its native res/refresh
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })

-- Specific monitors (from edit_here — generated by Dusky Monitor Wizard 20260504)
hl.monitor({ output = "DP-1", mode = "2560x1440@180.00200", position = "0x0", scale = 1.0 })
hl.monitor({ output = "DP-2", mode = "1920x1080@60.00000", position = "2560x0", scale = 1.0 })
hl.monitor({ output = "DP-4", mode = "2560x1440@180.00200", position = "0x0", scale = 1.0 })
hl.monitor({ output = "DP-5", mode = "1920x1080@60.00000", position = "2560x0", scale = 1.0 })

-- VRR (from source/monitors.conf)
-- vrr = 1 uses extra ~1W but makes idle feel smoother
hl.config({
	-- debug = {
	-- 	vfr = false,
	-- },
	misc = {
		vrr = 1,
		-- render_unfocused_fps = 1,
	},
})

hl.workspace_rule({ workspace = "1", monitor = "desc:AOC Q27G42XE 1O0R3HA007458", default = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:AOC Q27G42XE 1O0R3HA007458" })
hl.workspace_rule({ workspace = "3", monitor = "desc:AOC Q27G42XE 1O0R3HA007458" })
hl.workspace_rule({ workspace = "4", monitor = "desc:AOC Q27G42XE 1O0R3HA007458" })
hl.workspace_rule({ workspace = "5", monitor = "desc:AOC Q27G42XE 1O0R3HA007458" })
hl.workspace_rule({ workspace = "6", monitor = "desc:ViewSonic Corporation VG2448 V5E191920340" })
hl.workspace_rule({ workspace = "7", monitor = "desc:ViewSonic Corporation VG2448 V5E191920340" })
hl.workspace_rule({ workspace = "8", monitor = "desc:ViewSonic Corporation VG2448 V5E191920340" })
hl.workspace_rule({ workspace = "9", monitor = "desc:ViewSonic Corporation VG2448 V5E191920340", default = true })
hl.workspace_rule({ workspace = "10", monitor = "desc:ViewSonic Corporation VG2448 V5E191920340" })
