[meta]
name        = "system"
description = "System services and utilities"
os          = "linux"

[[packages]]
name   = "sddm"
system = "sddm"

[[packages]]
name   = "blueman"
system = "blueman"

[[packages]]
name   = "btrfs-assistant"
system = "btrfs-assistant"

[[packages]]
name   = "cups-pdf"
system = "cups-pdf"

[[packages]]
name   = "flatpak"
system = "flatpak"

[[packages]]
name   = "gnome-disk-utility"
system = "gnome-disk-utility"

[[packages]]
name   = "kopia"
system = "kopia"
optional = true

[[packages]]
name   = "polkit-kde-agent"
system = "polkit-kde-agent"

[[packages]]
name   = "reflector"
system = "reflector"

[[packages]]
name   = "tesseract"
system = "tesseract"

[[packages]]
name   = "tesseract-data-eng"
system = "tesseract-data-eng"

[[packages]]
name   = "chezmoi"
system = "chezmoi"
optional = true

[[packages]]
name   = "input-remapper-git"
system    = "input-remapper-git"

[[packages]]
name = "easyeffects"
system = "easyeffects"

[[packages]]
name = "lsp-plugins-lv2"
system = "lsp-plugins-lv2"

[[packages]]
name = "zam-plugins-lv2"
system = "zam-plugins-lv2"

[[packages]]
name = "mda.lv2"
system = "mda.lv2"

[[packages]]
name = "calf"
system = "calf"

[[scripts]]
name = "SDDM Theme"
file = "scripts/sddm-theme.sh"
when = "post_packages"
