[meta]
name        = "system"
description = "System services and utilities"
os          = "linux"

[[packages]]
name   = "sddm"
system = "sddm"

[[packages]]
name   = "blueman"
system = "blueman"

[[packages]]
name   = "bluez"
system = "bluez"

[[packages]]
name   = "ufw"
system = "ufw"

[[packages]]
name   = "btrfs-assistant"
system = "btrfs-assistant"

[[packages]]
name   = "cups-pdf"
system = "cups-pdf"

[[packages]]
name   = "flatpak"
system = "flatpak"

[[packages]]
name   = "gnome-disk-utility"
system = "gnome-disk-utility"

[[packages]]
name   = "kopia"
system = "kopia"
optional = true

[[packages]]
name   = "polkit-kde-agent"
system = "polkit-kde-agent"

[[packages]]
name   = "reflector"
system = "reflector"

[[packages]]
name   = "tesseract"
system = "tesseract"

[[packages]]
name   = "tesseract-data-eng"
system = "tesseract-data-eng"

[[packages]]
name   = "chezmoi"
system = "chezmoi"
optional = true

[[packages]]
name   = "input-remapper-git"
system    = "input-remapper-git"

[[packages]]
name = "easyeffects"
system = "easyeffects"

[[packages]]
name = "lsp-plugins-lv2"
system = "lsp-plugins-lv2"

[[packages]]
name = "zam-plugins-lv2"
system = "zam-plugins-lv2"

[[packages]]
name = "mda.lv2"
system = "mda.lv2"

[[packages]]
name = "calf"
system = "calf"

[[packages]]
name = "yay"
system = "yay"

[[packages]]
name = "paru"
system = "paru"
optional = true

[[scripts]]
name = "Configure Reflector mirrors"
file = "scripts/reflector-setup.sh"
when = "post_packages"

[[scripts]]
name = "SDDM Theme"
file = "scripts/sddm-theme.sh"
when = "post_packages"

[[scripts]]
name = "Configure UFW firewall"
file = "scripts/ufw-setup.sh"
when = "post_packages"

[[scripts]]
name = "Enable system services"
file = "scripts/enable-system-services.sh"
when = "post_packages"

[[scripts]]
name = "Enable user services"
file = "scripts/enable-user-services.sh"
when = "post_packages"

[[dotfiles]]
src = "files/.config/easyeffects/db"
target_linux = "~/.config/easyeffects/db"
target_mac = "~/.config/easyeffects/db"

[[dotfiles]]
src = "files/.config/input-remapper-2"
target_linux = "~/.config/input-remapper-2"
target_mac = "~/.config/input-remapper-2"

[[dotfiles]]
src = "files/.config/systemd/user"
target_linux = "~/.config/systemd/user"
target_mac = "~/.config/systemd/user"

[[dotfiles]]
src = "files/.config/mimeapps.list"
target_linux = "~/.config/mimeapps.list"
target_mac = "~/.config/mimeapps.list"

[[dotfiles]]
src = "files/.config/xdg-terminals.list"
target_linux = "~/.config/xdg-terminals.list"
target_mac = "~/.config/xdg-terminals.list"
