[meta]
name        = "hyprland"
description = "Hyprland compositor and session-specific stack (depends on wayland pack)"
os          = "linux"

[[packages]]
name   = "hyprland"
system = "hyprland"

[[packages]]
name   = "hypridle"
system = "hypridle"

[[packages]]
name   = "hyprlock"
system = "hyprlock"

[[packages]]
name   = "hyprpicker"
system = "hyprpicker"

[[packages]]
name   = "hyprpolkitagent"
system = "hyprpolkitagent"

[[packages]]
name   = "hyprshade"
system = "hyprshade"
optional = true

[[packages]]
name   = "waybar"
system = "waybar"

[[packages]]
name   = "swaync"
system = "swaync"

[[packages]]
name   = "wlogout"
system = "wlogout"

[[packages]]
name   = "swappy"
system = "swappy"
optional = true

[[packages]]
name   = "waypaper"
system = "waypaper"

[[packages]]
name   = "wev"
system = "wev"

[[packages]]
name   = "xdg-desktop-portal-hyprland"
system = "xdg-desktop-portal-hyprland"

[[packages]]
name   = "quickshell-overview-git"
system = "quickshell-overview-git"
optional = true

[[packages]]
name = "surfraw"
system = "surfraw"

[[packages]]
name = "python-pytesseract"
system = "python-pytesseract"

[[packages]]
name = "tesseract"
system = "tesseract"

[[packages]]
name = "tesseract-data-eng"
system = "tesseract-data-eng"

[[scripts]]
name = "Enable Hyprland user services"
file = "scripts/enable-hyprland-services.sh"
when = "post_packages"

[[dotfiles]]
src          = "files/.config/hypr"
target_linux = "~/.config/hypr"
target_mac   = "~/.config/hypr"

[[dotfiles]]
src          = "files/.config/swappy"
target_linux = "~/.config/swappy"
target_mac   = "~/.config/swappy"

[[dotfiles]]
src          = "files/.config/swaync"
target_linux = "~/.config/swaync"
target_mac   = "~/.config/swaync"

[[dotfiles]]
src          = "files/.config/wlogout"
target_linux = "~/.config/wlogout"
target_mac   = "~/.config/wlogout"

[[dotfiles]]
src          = "files/.config/waybar"
target_linux = "~/.config/waybar"
target_mac   = "~/.config/waybar"

[[dotfiles]]
src          = "files/.config/waypaper"
target_linux = "~/.config/waypaper"
target_mac   = "~/.config/waypaper"

[[dotfiles]]
src = "files/user_scripts"
target_linux = "~/user_scripts"
target_mac = "~/user_scripts"

[[dotfiles]]
src = "files/img/wallpapers"
target_linux = "~/img/wallpapers"
target_mac = "~/img/wallpapers"

[[dotfiles]]
src = "files/.local/share/applications/custom"
target_linux = "~/.local/share/applications/custom"
target_mac = "~/.local/share/applications/custom"
