-- MONITORS
-- Merged: source/monitors.conf + edit_here/source/monitors.conf
-- Specific monitor rules from edit_here override the fallback, but the
-- fallback is kept so hotplugged displays still work automatically.

-- Fallback: any display not matched below gets its native res/refresh
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })

-- Specific monitors (from edit_here — generated by Dusky Monitor Wizard 20260504)
hl.monitor({ output = "DP-1", mode = "2560x1440@180.00200", position = "0x0", scale = 1.0 })
hl.monitor({ output = "DP-2", mode = "1920x1080@60.00000", position = "2560x0", scale = 1.0 })
hl.monitor({ output = "DP-4", mode = "2560x1440@180.00200", position = "0x0", scale = 1.0 })
hl.monitor({ output = "DP-5", mode = "1920x1080@60.00000", position = "2560x0", scale = 1.0 })

-- VRR (from source/monitors.conf)
-- vrr = 1 uses extra ~1W but makes idle feel smoother
-- hl.config({
-- 	-- debug = {
-- 	-- 	vfr = false,
-- 	-- },
-- 	misc = {
-- 		vrr = 1,
-- 	},
-- })
