context.modules = [
    { name = libpipewire-module-filter-chain
      args = {
          node.description = "Minimal Noise Suppressed Microphone"
          media.name       = "Noise Suppression Source"
          filter.graph = {
              nodes = [
                  {
                      type   = ladspa
                      name   = rnnoise
                      plugin = librnnoise_ladspa
                      label  = noise_suppressor_mono
                  }
              ]
          }
          capture.props = {
              node.name        = "effect_input.rnnoise"
              node.passive     = true
              audio.position   = [ MONO ]
          }
          playback.props = {
              node.name        = "effect_output.rnnoise"
              media.class      = Audio/Source
              audio.position   = [ MONO ]
          }
      }
    }
]
