context.modules = [
    {
        name = libpipewire-module-filter-chain
        args = {
            node.description = "Split Equalizer Sink"
            media.name       = "Split Equalizer Sink"
            filter.graph = {
                nodes = [
                    {
                        type  = builtin
                        name  = eq
                        label = param_eq
                        config = {
                            filters = [
                                { type = bq_highshelf, freq = 0, gain = -10.0, q = 1.0 },
                                { type = bq_lowshelf, freq = 120, gain = 15.0, q = 0.7 },
                            ]
                        }
                    }
                ]
                links = []
            }
            audio.channels = 2
            audio.position = [ FL FR ]
            capture.props = {
                node.name   = "split_input.eq"
                media.class = Audio/Sink
            }
            playback.props = {
                node.name   = "split_output.eq"
                node.passive = true
            }
        }
    }
]
