[meta]
name        = "yazi"
description = "Terminal file manager with preview support"
os          = "any"

[[packages]]
name   = "yazi"
system = "yazi"

[[packages]]
name   = "imagemagick"
system = "imagemagick"

[[packages]]
name   = "fd"
system = "fd"

[[packages]]
name   = "ripgrep"
system = "ripgrep"

[[packages]]
name   = "zoxide"
system = "zoxide"

[[packages]]
name   = "trash-cli"
system = "trash-cli"

[[packages]]
name = "ffmpeg"
system = "ffmpeg"

[[packages]]
name = "7zip"
system = "7zip"

[[packages]]
name = "poppler"
system = "poppler"

[[packages]]
name = "jq"
system = "jq"

[[packages]]
name = "dragon-drop"
system = "dragon-drop"

[[dotfiles]]
src          = "files/.config/yazi"
target_linux = "~/.config/yazi"
target_mac   = "~/.config/yazi"
